#!/bin/bash

# Quit if misued
if [ $# -lt 2 ] ; then
  echo "usage: filter target_files ... s/search/replace/"
  exit
fi

# Store the final argument (the SED filter)
SED=${!#}
# Remove the final argument from $@
set -- "${@:1:$(($#-1))}"

# Explain what we're going to do...
for var
do
    echo $var$'\t'-\>  $'\t'`echo $var | sed "$SED"`
done

# Prompt the user
read -r -p "Rename these files? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
        # Commit changes
        for var
        do
            mv "$var" "`echo $var | sed "$SED"`"
        done
        ;;
    *)
        ;;
esac
