#!/bin/bash

DRY=false

# Parse the options
while getopts "ds:" flag 
do 
    if [ $flag == "d" ] ; then
        DRY=true
    fi
    #if [ $flag == "s" ] ; then
    #    SEARCH=$OPTARG
    #fi
    #echo "$flag" $OPTIND $OPTARG 
done

shift $((${OPTIND}-1))

FILTER="${@: -1}"

#echo DRY=$DRY
#echo FILTER=$FILTER

while [ $# -gt 1 ] ; do
    echo mv \"$1\" \"`echo $1 | sed "$FILTER"`\"
    shift
done

